### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by jmontanholi** [jmontanholi/JavaScriptCapstone-joao-sebastian#19]
Choose images, text, icons, fonts.

**Comment by smunozmo** [comment]
Selected assets for styling:

### Bootstrap 
- https://getbootstrap.com/docs/5.0/getting-started/introduction/

### Font Awesome 
- https://getbootstrap.com/docs/5.0/getting-started/introduction/

### Google Fonts 
- https://fonts.google.com/specimen/Comic+Neue?query=comic#license
